/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package source.mysql;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
//        MySQLSourceTask classUnderTest = new MySQLSourceTask();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
