/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hstream;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.SQLException;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.testcontainers.containers.GenericContainer;

class SourceMysqlTest {
    GenericContainer<?> mysql;
    Connection conn;
    HStreamHelper helper;

    @BeforeEach
    void setup(TestInfo testInfo) throws Exception {
        // setup HStreamDB
        helper = new HStreamHelper(testInfo);
        // setup mysql
        mysql = Utils.makeMysql();
        mysql.start();

        conn = Utils.getMysqlConn(mysql.getMappedPort(3306));
        prepareTable();
        System.out.println("Mysql started");
    }

    @AfterEach
    void tearDown() throws Exception {
        mysql.stop();
        helper.close();
    }

    void prepareTable() throws SQLException {
        var stmt = conn.createStatement();
        stmt.execute("create database d1");
        stmt.execute("create table d1.person (id int primary key, name varchar(256), age int)");
    }

    void createSourceConnector() throws UnknownHostException {
        var hostname = InetAddress.getLocalHost().getHostName();
        var sql = "create source connector ss01 from mysql with" +
                "(\"host\" = \"" + hostname + "\"," +
                "\"port\" = " + mysql.getMappedPort(3306) + "," +
                "\"user\" = \"root\"," +
                "\"password\" = \"password\"," +
                "\"database\" = \"d1\"," +
                "\"table\" = \"person\"," +
                "\"stream\" = \"s01\");";
        helper.createConnector("ss01", sql);
    }

    @Test
    void testFullReplication() throws Exception {
        // prepared data
        var ps = conn.prepareStatement("insert into d1.person values (?, ?, ?)");
        ps.setObject(1, 1);
        ps.setObject(2, "John");
        ps.setObject(3, 20);
        ps.execute();
        System.out.println("prepared data");
        createSourceConnector();
        Thread.sleep(30000);
        var result = helper.listConnectors();
        Assertions.assertEquals(result.size(), 1);
        // check the stream
        var res = Utils.readStream(helper.client, "s01", 5);
        Assertions.assertEquals(1, res.size());
        helper.deleteConnector("ss01");
    }
}
