/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hstream;

import io.hstream.external.Sqlserver;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;

class SourceSqlserverTest {
  Sqlserver sqlserver;
  HStreamHelper helper;

  @BeforeEach
  void setup(TestInfo testInfo) throws Exception {
    helper = new HStreamHelper(testInfo);
    sqlserver = new Sqlserver();
  }

  @AfterEach
  void tearDown() throws Exception {
    sqlserver.close();
    helper.close();
  }

  @Test
  void testFullSync() throws Exception {
    Utils.testSourceFullSync(helper, sqlserver);
  }
}
