/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package source.mysql;

import io.debezium.engine.ChangeEvent;
import io.debezium.engine.DebeziumEngine;
import io.debezium.engine.format.Json;
import io.debezium.engine.spi.OffsetCommitPolicy;
import io.hstream.HRecord;
import io.hstream.SourceTaskContext;
import io.hstream.debezium.DebeziumOffsetBackingStore;
import io.hstream.debezium.DebeziumRecordConsumer;
import java.util.Properties;
import io.hstream.SourceTask;

class MySQLSourceTask implements SourceTask {
    DebeziumEngine<ChangeEvent<String, String>> engine;
    SourceTaskContext ctx;

    @Override
    public void init(HRecord cfg, SourceTaskContext ctx) {
        try {
            System.out.println("cfg:" + cfg.toJsonString());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        this.ctx = ctx;
        final Properties props = new Properties();
        props.setProperty("name", "engine");
        props.setProperty("connector.class", "io.debezium.connector.mysql.MySqlConnector");
        props.setProperty("offset.storage", "io.hstream.debezium.DebeziumOffsetBackingStore");
        DebeziumOffsetBackingStore.setKvStore(ctx.getKvStore());
        props.setProperty("offset.flush.interval.ms", "10000");
        // schema
        props.setProperty("key.converter", "org.apache.kafka.connect.json.JsonConverter");
        props.setProperty("key.converter.schemas.enable", "false");
        props.setProperty("value.converter", "org.apache.kafka.connect.json.JsonConverter");
        props.setProperty("value.converter.schemas.enable", "false");
        /* begin connector properties */
        props.setProperty("database.hostname", cfg.getString("hostname"));
        props.setProperty("database.port", cfg.getString("port"));
        props.setProperty("database.user", cfg.getString("user"));
        props.setProperty("database.password", cfg.getString("password"));
        props.setProperty("database.server.id", "85744");
        props.setProperty("database.server.name", "my-app-connector");
        props.setProperty("database.history",
                "io.debezium.relational.history.FileDatabaseHistory");
        props.setProperty("database.history.file.filename", cfg.getString("dbHistoryPath"));
        // props.setProperty("database.max.batch.size", "3");

        // Create the engine with this configuration ...
        engine = DebeziumEngine.create(Json.class)
                .using(props)
                .using(OffsetCommitPolicy.always())
                .notifying(new DebeziumRecordConsumer(ctx))
                .build();
    }

    @Override
    public void run() {
        engine.run();
    }

    @Override
    public void stop() throws Exception {
        engine.close();
    }
}