/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sink.jdbc;

import io.hstream.io.TaskRunner;
import io.hstream.io.impl.SinkTaskContextImpl;

public class App {
    public static void main(String[] args) {
        new TaskRunner().run(args, new JdbcSinkTask(), new SinkTaskContextImpl());
    }
}
