/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hstream.io;

import io.hstream.HRecord;

public interface SourceTask {
    void init(HRecord config, SourceTaskContext ctx);
    void run();
    void stop() throws Exception;
}