/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package source.debezium;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
//        MySQLSourceTask classUnderTest = new MySQLSourceTask();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
