/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hstream;

public interface SourceTask {
    void init(HRecord config, SourceTaskContext ctx);
    void run();
    void stop() throws Exception;
}